### PR TITLE
40 undeprecated guard

### PR DESCRIPTION
**Pull request by Pixailz**
minor fix

### CODE REVIEW

**Review by clinche — APPROVED** [review]

**Comment by Pixailz** [comment]
ooh i see, you redirect to `/login` with a query containing current url tryed am i correct ? @clinche

**Comment by Pixailz** [comment]
make a review request so i can merge it

**Comment by clinche** [comment]
Yes absolutely

**Comment by clinche** [comment]
Yes absolutely

I can't ask you a review

**Review by clinche — APPROVED** [review]

**Pull request merged**
