### PR TITLE
refact extern login front page

### PR DESCRIPTION
**Pull request by Ycaro02**

### CODE REVIEW

**Comment by Pixailz** [comment]
Should wait for https://github.com/Pixailz/ft_transcendence/pull/187 as it fix some bugs

**Review by RuBeeN-cmd — APPROVED** [review]
Yes I'm good

**Review by RuBeeN-cmd — APPROVED** [review]
Nice

**Review by RuBeeN-cmd — APPROVED** [review]
ok

**Review by clinche — APPROVED** [review]
Noice regex

**Pull request merged**
