### PR TITLE
56 front add environments (fix CI)

### PR DESCRIPTION
**Pull request by Pixailz**
see this [PR](https://github.com/Pixailz/ft_transcendence/pull/57) for more informations.

this PR fix the CI test because it use the setup script to setup .env file, and setup have been changed ..

should be good now :crossed_fingers:

### CODE REVIEW

**Review by clinche — CHANGES_REQUESTED** [review]
I can't test it but it should work fine ✔️

What I noticed though is since an api app can not have more than 1 redirect uri, we might just as well create two apps, a dev and a prod, and consequently add two more env variables to take in account we now have two apps 👀

**Review by clinche — COMMENTED** [review]
The above message wasn't meant to be defnitive I would have liked feedbacks on this

**Comment by Pixailz** [comment]
i don't see the change you requested @clinche and i don't understand what do you mean by two apps.

the 42api can have two redirect uri in the settings so it's just choosing the correct one at runtime :)

**Comment by clinche** [comment]
It was a miss click but I can't go change it (actually my phone)

And does it work for you? Last time I tried different uri it didn't work but if it works that's better yes 👍

**Pull request merged**
