### PR TITLE
[deploy] patch setup redirecturl

### PR DESCRIPTION
**Pull request by clinche**
also we need to remove the port form the `HOST_IP` variable as prod website is accessed on 443

### CODE REVIEW

**Comment by Pixailz** [comment]
this is not the prod website, there's a problem on the redirect_uri, i let you fix this one.

**Review by Pixailz — CHANGES_REQUESTED** [review]
nope

**Comment by clinche** [comment]
@Pixailz pr not valid but you still need to remove `:4469` from the `HOST_IP`

**Comment by Pixailz** [comment]
Working now @clinche :)

but the main branch is not clean (don't work..)

**Comment by clinche** [comment]
Main branch is clean, error due to expired secret

**Pull request closed without merging**
